### PR TITLE
somoslegalshield search feature test

### PR DESCRIPTION
**Pull request by roppel5ls**
This is to test the search feature on somoslegalshield.com. Got rid of the un-needed config file.

### CODE REVIEW

**Comment by Bradern8t0r** [comment]
LGTM

**Comment by robertvazquezlegalshield** [comment]
Me parece bien (LTGM)

**Comment by roppel5ls** [comment]
Approved - @Bradern8t0r @robertvazquezlegalshield

**Comment by Gregorma** [comment]
LGTM

**Pull request merged**
